name: Build

on:
  push:
    branches:
      - main

jobs:
  Build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.10.1'
      - uses: r-lib/actions/setup-r@v2
        with:
            r-version: '4.2.0'

      - name: Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get install libpoppler-cpp-dev libcurl4-openssl-dev libglu1-mesa-dev libmagick++-dev libharfbuzz-dev libfribidi-dev

      - name: Install pandoc filters
        run: |
          python -m pip install --upgrade pip
          pip install pandoc-fignos pandoc-eqnos pandoc-tablenos pandoc-secnos pandoc-xnos
          which pandoc pandoc-fignos pandoc-eqnos pandoc-tablenos pandoc-secnos pandoc-xnos

      - name: Install LaTeX
        run: |
          sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: Install R packages
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: build project
        run: make

      - name: prepare deployment
        run: |
          mv docs/manuscript.html docs/index.html
      
      - name: Deploy gh_pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          SINGLE_COMMIT: true
